DROP TABLE ACCESS_TOKEN;

DROP TABLE ADDRESS;
DROP SEQUENCE ADDRESS_SEQ;

DROP TABLE EVENT;
DROP SEQUENCE EVENT_SEQ;

DROP TABLE EVENT_TO_HARDWARE;
DROP SEQUENCE EVENT_TO_HARDWARE_SEQ;

DROP TABLE EVENT_TO_LOCATION;
DROP SEQUENCE EVENT_TO_LOCATION_SEQ;

DROP TABLE EVENT_TO_SOFTWARE;
DROP SEQUENCE EVENT_TO_SOFTWARE_SEQ;

DROP TABLE EVENT_TO_USER;
DROP SEQUENCE EVENT_TO_USER_SEQ;

DROP TABLE HARDWARE;
DROP SEQUENCE HARDWARE_SEQ;

DROP TABLE HARDWARE_TO_SOFTWARE;
DROP SEQUENCE HARDWARE_TO_SOFTWARE_SEQ;

DROP TABLE LOCATION;
DROP SEQUENCE LOCATION_SEQ;

DROP TABLE REF_CONDITION;

DROP TABLE REF_HARDWARE_TYPE;

DROP TABLE REF_PERMISSION;
DROP SEQUENCE REF_PERMISSION_SEQ;

DROP TABLE REF_PERMISSION_TO_ROLE;
DROP SEQUENCE REF_PERMISSION_TO_ROLE_SEQ;

DROP TABLE ROLE;
DROP SEQUENCE ROLE_SEQ;

DROP TABLE ROLE_TO_USER;
DROP SEQUENCE ROLE_TO_USER_SEQ;

DROP TABLE SMTP;
DROP SEQUENCE SMTP_SEQ;

DROP TABLE SOFTWARE;
DROP SEQUENCE SOFTWARE_SEQ;

DROP TABLE TEAM;
DROP SEQUENCE TEAM_SEQ;

DROP TABLE TEAM_TO_USER;
DROP SEQUENCE TEAM_TO_USER_SEQ;

DROP TABLE USER;
DROP SEQUENCE USER_SEQ;

ALTER TABLE ACCESS_TOKEN DROP CONSTRAINT FK_ACCESS_TOKEN_USER_KEY;
ALTER TABLE EVENT_TO_HARDWARE DROP CONSTRAINT FK_EVENT_TO_HARDWARE_EVENT_ID;
ALTER TABLE EVENT_TO_HARDWARE DROP CONSTRAINT FK_EVENT_TO_HARDWARE_HARDWARE_ID;
ALTER TABLE EVENT_TO_LOCATION DROP CONSTRAINT FK_EVENT_TO_LOCATION_EVENT_ID;
ALTER TABLE EVENT_TO_LOCATION DROP CONSTRAINT FK_EVENT_TO_LOCATION_LOCATION_ID;
ALTER TABLE EVENT_TO_SOFTWARE DROP CONSTRAINT FK_EVENT_TO_SOFTWARE_EVENT_ID;
ALTER TABLE EVENT_TO_SOFTWARE DROP CONSTRAINT FK_EVENT_TO_SOFTWARE_SOFTWARE_ID;
ALTER TABLE EVENT_TO_USER DROP CONSTRAINT FK_EVENT_TO_USER_EVENT_ID;
ALTER TABLE EVENT_TO_USER DROP CONSTRAINT FK_EVENT_TO_USER_USER_ID;
ALTER TABLE HARDWARE DROP CONSTRAINT FK_HARDWARE_LOCATION_ID;
ALTER TABLE HARDWARE DROP CONSTRAINT FK_HARDWARE_USER_ID;
ALTER TABLE HARDWARE DROP CONSTRAINT FK_HARDWARE_CONDITION;
ALTER TABLE HARDWARE_TO_SOFTWARE DROP CONSTRAINT FK_HARDWARE_TO_SOFTWARE_HARDWARE_ID;
ALTER TABLE HARDWARE_TO_SOFTWARE DROP CONSTRAINT FK_HARDWARE_TO_SOFTWARE_SOFTWARE_ID;
ALTER TABLE LOCATION DROP CONSTRAINT FK_LOCATION_ADDRESS_ID;
ALTER TABLE REF_PERMISSION_TO_ROLE DROP CONSTRAINT FK_REF_PERMISSION_TO_ROLE_PERMISSION_ID;
ALTER TABLE REF_PERMISSION_TO_ROLE DROP CONSTRAINT FK_REF_PERMISSION_TO_ROLE_ROLE_ID;
ALTER TABLE ROLE_TO_USER DROP CONSTRAINT FK_ROLE_TO_USER_ROLE_ID;
ALTER TABLE ROLE_TO_USER DROP CONSTRAINT FK_ROLE_TO_USER_USER_ID;
ALTER TABLE TEAM_TO_USER DROP CONSTRAINT FK_TEAM_TO_USER_USER_ID;
ALTER TABLE TEAM_TO_USER DROP CONSTRAINT FK_TEAM_TO_USER_TEAM_ID;
ALTER TABLE USER DROP CONSTRAINT FK_USER_ROLE_ID;
