-- Remove Original Table and Sequence

DROP TABLE EVENT_TO_HARDWARE;
DROP SEQUENCE EVENT_TO_HARDWARE_SEQ;
-- Create Table


CREATE TABLE EVENT_TO_HARDWARE (
    KEY                NUMBER(10) NOT NULL,
    EVENT_ID           NUMBER(10) NOT NULL,
    HARDWARE_ID        NUMBER(10) NOT NULL,
    CONSTRAINT EVENT_TO_HARDWARE_PK PRIMARY KEY ( KEY ));

CREATE SEQUENCE EVENT_TO_HARDWARE_SEQ;


-- Sample Select Statement

SELECT
    KEY, EVENT_ID, HARDWARE_ID 
from EVENT_TO_HARDWARE
WHERE
    KEY = 0;

-- PROTECTED CODE -->