-- Remove Original Table and Sequence

DROP TABLE EVENT_TO_LOCATION;
DROP SEQUENCE EVENT_TO_LOCATION_SEQ;
-- Create Table


CREATE TABLE EVENT_TO_LOCATION (
    KEY                NUMBER(10) NOT NULL,
    EVENT_ID           NUMBER(10) NOT NULL,
    LOCATION_ID        NUMBER(10) NOT NULL,
    CONSTRAINT EVENT_TO_LOCATION_PK PRIMARY KEY ( KEY ));

CREATE SEQUENCE EVENT_TO_LOCATION_SEQ;


-- Sample Select Statement

SELECT
    KEY, EVENT_ID, LOCATION_ID 
from EVENT_TO_LOCATION
WHERE
    KEY = 0;

-- PROTECTED CODE -->