-- Remove Original Table and Sequence

DROP TABLE EVENT_TO_SOFTWARE;
DROP SEQUENCE EVENT_TO_SOFTWARE_SEQ;
-- Create Table


CREATE TABLE EVENT_TO_SOFTWARE (
    KEY                NUMBER(10) NOT NULL,
    EVENT_ID           NUMBER(10) NOT NULL,
    SOFTWARE_ID        NUMBER(10) NOT NULL,
    CONSTRAINT EVENT_TO_SOFTWARE_PK PRIMARY KEY ( KEY ));

CREATE SEQUENCE EVENT_TO_SOFTWARE_SEQ;


-- Sample Select Statement

SELECT
    KEY, EVENT_ID, SOFTWARE_ID 
from EVENT_TO_SOFTWARE
WHERE
    KEY = 0;

-- PROTECTED CODE -->