-- Remove Original Table and Sequence

DROP TABLE GOOGLE_CLIENT;
DROP SEQUENCE GOOGLE_CLIENT_SEQ;
-- Create Table


CREATE TABLE GOOGLE_CLIENT (
    KEY                NUMBER(10) NOT NULL,
    CLIENT_ID          VARCHAR2(100),
    CLIENT_SECRET      VARCHAR2(50),
    CONSTRAINT GOOGLE_CLIENT_PK PRIMARY KEY ( KEY ));

CREATE SEQUENCE GOOGLE_CLIENT_SEQ;


-- Sample Select Statement

SELECT
    KEY, CLIENT_ID, CLIENT_SECRET 
from GOOGLE_CLIENT
WHERE
    KEY = 0;

-- PROTECTED CODE -->