-- Remove Original Table and Sequence

DROP TABLE HARDWARE_TO_SOFTWARE;
DROP SEQUENCE HARDWARE_TO_SOFTWARE_SEQ;
-- Create Table


CREATE TABLE HARDWARE_TO_SOFTWARE (
    KEY                NUMBER(10) NOT NULL,
    HARDWARE_ID        NUMBER(10) NOT NULL,
    SOFTWARE_ID        NUMBER(10) NOT NULL,
    CONSTRAINT HARDWARE_TO_SOFTWARE_PK PRIMARY KEY ( KEY ));

CREATE SEQUENCE HARDWARE_TO_SOFTWARE_SEQ;


-- Sample Select Statement

SELECT
    KEY, HARDWARE_ID, SOFTWARE_ID 
from HARDWARE_TO_SOFTWARE
WHERE
    KEY = 0;

-- PROTECTED CODE -->