-- Remove Original Table and Sequence

DROP TABLE HARDWARE_TO_SOFTWARE;
DROP SEQUENCE HARDWARE_TO_SOFTWARE_SEQ;
-- Create Table


CREATE TABLE HARDWARE_TO_SOFTWARE (
    HARDWARE_ID        NUMBER(10) NOT NULL,
    SOFTWARE_ID        NUMBER(10) NOT NULL,
    CONSTRAINT HARDWARE_TO_SOFTWARE_PK PRIMARY KEY ( HARDWARE_ID, SOFTWARE_ID ));

CREATE SEQUENCE HARDWARE_TO_SOFTWARE_SEQ;


-- Sample Select Statement

SELECT
    HARDWARE_ID, SOFTWARE_ID 
from HARDWARE_TO_SOFTWARE
WHERE
    HARDWARE_ID = 0;

-- PROTECTED CODE -->