-- Remove Original Table and Sequence

DROP TABLE REF_PERMISSION;
DROP SEQUENCE REF_PERMISSION_SEQ;
-- Create Table


CREATE TABLE REF_PERMISSION (
    KEY                NUMBER(10) NOT NULL,
    CODE               VARCHAR2(40) NOT NULL,
    DESCRIPTION        VARCHAR2(2000) NOT NULL,
    CONSTRAINT REF_PERMISSION_PK PRIMARY KEY ( KEY ));

CREATE SEQUENCE REF_PERMISSION_SEQ;


-- Sample Select Statement

SELECT
    KEY, CODE, DESCRIPTION 
from REF_PERMISSION
WHERE
    KEY = 0;

-- PROTECTED CODE -->