-- Remove Original Table and Sequence

DROP TABLE REF_PERMISSION_TO_ROLE;
DROP SEQUENCE REF_PERMISSION_TO_ROLE_SEQ;
-- Create Table


CREATE TABLE REF_PERMISSION_TO_ROLE (
    KEY                NUMBER(10) NOT NULL,
    PERMISSION_ID      NUMBER(10) NOT NULL,
    ROLE_ID            NUMBER(10) NOT NULL,
    CONSTRAINT REF_PERMISSION_TO_ROLE_PK PRIMARY KEY ( KEY ));

CREATE SEQUENCE REF_PERMISSION_TO_ROLE_SEQ;


-- Sample Select Statement

SELECT
    KEY, PERMISSION_ID, ROLE_ID 
from REF_PERMISSION_TO_ROLE
WHERE
    KEY = 0;

-- PROTECTED CODE -->